# Generated by Django 4.2.16 on 2025-03-24 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_remplissage', models.DateField()),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('profession', models.CharField(max_length=100)),
                ('arrondissement', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=100)),
                ('hypertension', models.BooleanField(default=False)),
                ('diabete', models.BooleanField(default=False)),
                ('asthme', models.BooleanField(default=False)),
                ('hiv_hbs_hcv', models.BooleanField(default=False)),
                ('tatoue', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('nombre_dons', models.IntegerField(default=1)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
