# Generated by Django 4.2.16 on 2025-04-07 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'Donneur', 'verbose_name_plural': 'Donneurs'},
        ),
        migrations.AlterField(
            model_name='donor',
            name='arrondissement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_remplissage',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='nombre_dons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
